import acrodance1 from "$lib/Regular/Dance/acrodance1.jpg";
import acrodance2 from "$lib/Regular/Dance/acrodance2.jpg";
import ballet1 from "$lib/Regular/Dance/ballet1.jpg";
import ballet2 from "$lib/Regular/Dance/ballet2.jpg";
import combo1 from "$lib/Regular/Dance/combo1.jpg";
import combo2 from "$lib/Regular/Dance/combo2.jpg";
import contemporary1 from "$lib/Regular/Dance/contemporary1.jpg";
import crisscrosskinder from "$lib/Regular/Dance/crisscrosskinder.jpg";
import hiphop1 from "$lib/Regular/Dance/hiphop1.jpg";
import hiphop2 from "$lib/Regular/Dance/hiphop2.jpg";
import jazz1 from "$lib/Regular/Dance/jazz1.jpg";
import jazz2 from "$lib/Regular/Dance/jazz2.jpg";
import modernmini from "$lib/Regular/Dance/modernmini.jpg";
import samplerbjg1 from "$lib/Regular/Dance/samplerbjg1.jpg";
import samplerbjg2 from "$lib/Regular/Dance/samplerbjg2.jpg";
import samplerbtg1 from "$lib/Regular/Dance/samplerbtg1.jpg";
import samplerbtg2 from "$lib/Regular/Dance/samplerbtg2.jpg";
import danceteamprep1 from "$lib/Regular/Dance/danceteamprep1.jpg";
import leadsjumpsturns1 from "$lib/Regular/Dance/leadsjumpsturns1.jpg";
import tap1 from "$lib/Regular/Dance/tap1.jpg";

export const load = async ({ locals}) => {

    //Set page data
    const cards = [
        {
            id: "crisscross",
            title: "Criss Cross Kinder",
            subclass: "BALLET, JAZZ",
            description: "Criss Cross Kinder Combo is an introductory class focusing on basic ballet, jazz, and tap technique. Short combinations will be taught to improve cognitive and social development. Basic technique is still being instilled to the dancer in Criss Cross Kinder Combo. Repetition of movement is important as well as learning rhythm and time.  The kinder dancers will learn two routines throughout the year. One will be performed for the holiday show and the other will be performed at the summer recital.",
            notice: "",
            src: crisscrosskinder,
            alt: "Tap Shoes",
            ages: "5-6 Years",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Black Leotard, Pink Tights, Pink Ballet Shoes, Black Jazz Shoes, Black Tap Shoes, Hair in Bun",
            href: "",
            name: "Criss Cross Kinder",
        },
        {
            id: "combo",
            title: "Combo 1",
            subclass: "BALLET, JAZZ, TAP",
            description: "Combo 1 includes Tap, Ballet & Jazz and is designed to build on basic movements, but can also be appropriate for beginner dancers just starting out. Small combinations will be taught at the barre, across the floor and in the center of the classroom to teach space awareness, formation changes as a team, individual responsibility and memory training. The Combo class will learn one routine for the holiday show and one routine for the summer recital.",
            notice: "",
            src: combo1,
            alt: "2 Kids Hugging",
            ages: "7-9 Years",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Black Leotard, Pink Tights, Pink Ballet Shoes, Black Jazz Shoes, Black Tap Shoes, Hair in Bun",
            href: "",
            name: "Combo 1",
        },
        {
            id: "",
            title: "Combo 2",
            subclass: "BALLET, JAZZ, TAP",
            description: "Combo 2 is the continuation of the basic movements learned in Combo 1, still focusing on Tap, Ballet & Jazz. The Combo 2 dancers will learn at a quicker pace and learn intermediate movements and combinations. This class will learn one routine for the holiday show and one routine for the summer recital.",
            notice: "*Completion of Combo 1 Required",
            src: combo2,
            alt: "Mentor and Kid Tap Dancing",
            ages: "7-9 Years",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Black Leotard, Pink Tights, Pink Ballet Shoes, Black Jazz Shoes, Black Tap Shoes, Hair in Bun",
            href: "",
            name: "Combo 2",
        },
        {
            id: "acrodance",
            title: "Acro Dance 1",
            subclass: "BALLET, JAZZ, TUMBLING, PARTNER WORK",
            description: "Acro Dance 1 combines the grace and balance of ballet, the fun and energetic styles of jazz, and the strength and flight of gymnastics tumbling. Students will partake in ballet, jazz, acro partner work, flexibility exercises, strengthening exercises and tumbling in both gym and dance studio. Acro Dance class will learn one routine for the holiday show and one routine for the summer recital.",
            notice: "",
            src: acrodance1,
            alt: "Hand Stand",
            ages: "7 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Dance Leotard (color optional), Black leggings, No shoes",
            href: "",
            name: "Acro Dance 1",
        },
        {
            id: "",
            title: "Acro Dance 2",
            subclass: "BALLET, JAZZ, TUMBLING, PARTNER WORK",
            description: "Acro Dance 2 is the continuation of the basic movements learned in Acro Dance 1. The Acro Dance 2 students will learn more advanced partner work, higher level tumbling and advanced strength and flexibility exercises creating stronger and leaner muscles. The Acro Dance 2 students will learn intricate movements and become introduced to group work. Each individual is responsible for their role as part of the puzzle. Everyone's strengths are important to the group as a whole and play a vital role in the creative choreography, strength, flexibility and movements. Acro Dance 2 will learn one routine for the holiday show and one routine for the summer recital.   ",
            notice: "*Completion of Acro Dance 1 Required",
            src: acrodance2,
            alt: "Acro",
            ages: "7 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Dance Leotard (color optional), Black leggings, No shoes",
            href: "",
            name: "Acro Dance 2",
        },
        {
            id: "samplerbjg",
            title: "Sampler BJG 1",
            subclass: "BALLET, JAZZ, GYMNASTICS",
            description: "Can't decide between gymnastics and dance? Now you don't need to. We have the convenience of offering three classes in one! Ballet and Jazz will take place the first half of class in the studio and gymnastics the last half in the Big gym. Levels are based on experience. The gymnastics portion of the class will include all events (vault, bars, beam, floor for girls) & (pommel, rings, vault, high bar, floor and pbars for boys).",
            notice: "*Level 1 is an introduction class, focusing on the fundamentals of each genre.",
            src: samplerbjg1,
            alt: "Balancing on a Bar",
            ages: "7-11 Years",
            duration: "1 Hour",
            payment: "$95/Month",
            note: "Attire: Gymnastics Leotard (color optional), Dance shorts, skirt or leggings (to wear in dance class), Pink Ballet Shoes, Nude Jazz Shoes, Hair pulled out of face.",
            href: "",
            name: "Sampler BJG 1",
        },
        {
            id: "",
            title: "Sampler BJG 2",
            subclass: "BALLET, JAZZ, GYMNASTICS",
            description: "Can't decide between gymnastics and dance? Now you don't need to. We have the convenience of offering three classes in one! Ballet and Jazz will take place the first half of class in the studio and gymnastics the last half in the Big gym. Levels are based on experience. The gymnastics portion of the class will include all events (vault, bars, beam, floor for girls) & (pommel, rings, vault, high bar, floor and pbars for boys).",
            notice: "*Level 2 students must have 2 years experience in all three genres.",
            src: samplerbjg2,
            alt: "Bars and Bar Balancing",
            ages: "7-11 Years",
            duration: "1 Hour",
            payment: "$95/Month",
            note: "Attire: Gymnastics Leotard (color optional), Dance shorts, skirt or leggings (to wear in dance class), Pink Ballet Shoes, Nude Jazz Shoes, Hair pulled out of face.",
            href: "",
            name: "Sampler BJG 2",
        },
        {
            id: "samplerbtg",
            title: "Sampler BTG 1",
            subclass: "BALLET, TAP, GYMNASTICS",
            description: "Can't decide between gymnastics and dance? Now you don't need to. We have the convenience of offering three classes in one! Ballet and Tap will take place the first half of class in the studio and gymnastics the last half in the Big gym. Levels are based on experience. The gymnastics portion of the class will include all events (vault, bars, beam, floor for girls) & (pommel, rings, vault, high bar, floor and pbars for boys).",
            notice: "*Level 1 is an introduction class, focusing on the fundamentals of each genre.",
            src: samplerbtg1,
            alt: "Mentor and Kids Stretching Arms High",
            ages: "7-11 Years",
            duration: "1 Hour",
            payment: "$95/Month",
            note: "Attire: Gymnastics Leotard (color optional), Dance shorts, skirt or leggings (to wear in dance class), Pink Ballet Shoes, Nude Jazz Shoes, Hair pulled out of face.",
            href: "",
            name: "Sampler BTG 1",
        },
        {
            id: "",
            title: "Sampler BTG 2",
            subclass: "BALLET, TAP, GYMNASTICS",
            description: "Can't decide between gymnastics and dance? Now you don't need to. We have the convenience of offering three classes in one! Ballet and Tap will take place the first half of class in the studio and gymnastics the last half in the Big gym. Levels are based on experience. The gymnastics portion of the class will include all events (vault, bars, beam, floor for girls) & (pommel, rings, vault, high bar, floor and pbars for boys).",
            notice: "*Level 2 students must have 2 years experience in all three genres.",
            src: samplerbtg2,
            alt: "Competition Ballet Dance",
            ages: "7-11 Years",
            duration: "1 Hour",
            payment: "$95/Month",
            note: "Attire: Gymnastics Leotard (color optional), Dance shorts, skirt or leggings (to wear in dance class), Pink Ballet Shoes, Nude Jazz Shoes, Hair pulled out of face.",
            href: "",
            name: "Sampler BTG 2",
        },
        {
            id: "ballet",
            title: "Ballet 1",
            subclass: "",
            description: "Ballet 1 introduces students to the foundations of barre work in order to develop proper alignment and classical technique. Simple movements will be devoloped across the floor and during center work. Ballet 1 will learn one routine for the holiday show and one routine for the summer recital.",
            notice: "",
            src: ballet1,
            alt: "2 Ballet Students Sitting",
            ages: "7 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Black Leotard, Pink Tights, Pink Ballet Shoes, Hair in Bun",
            href: "",
            name: "Ballet 1",
        },
        {
            id: "",
            title: "Ballet 2",
            subclass: "",
            description: "Ballet 2 students continue to work on traveling steps with an introduction to grand allegro. At this level an emphasis is placed on turning, jumping, and linking steps. Basic terminology and body placement will become familiar to the ballerina. Ballet 2 will learn one routine for the holiday show and one routine for the summer recital.",
            notice: "*Completion of Ballet 1 Required",
            src: ballet2,
            alt: "Ballet Students Right Leg Stretch",
            ages: "7 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Black Leotard, Pink Tights, Pink Ballet Shoes, Hair in Bun",
            href: "",
            name: "Ballet 2",
        },
        {
            id: "jazz",
            title: "Jazz 1",
            subclass: "",
            description: "Jazz is a well known dance technique made up of Broadway dance to swing dance, to fun hip hop like isolated movements and even fast lyrical movements. The fun just pours out during high energy class. Jazz 1 are beginner dancers becoming familiar with jazz choreography and energetic movements or continuing Jazz dancers from Jazzy Jazzers. Jazz 1 will learn one routine for the holiday show and one routine for the summer recital.",
            notice: "",
            src: jazz1,
            alt: "Black and White Jazz Performance",
            ages: "7 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Black Leotard, Black or Nude Tights, Nude Jazz Shoes",
            href: "",
            name: "Jazz 1",
        },
        {
            id: "",
            title: "Jazz 2",
            subclass: "",
            description: "Jazz 2 dancers are becoming familiar with jazz technique  and energetic movements while learning more challenging choreography and higher level leaps, jumps and turns.  Jazz 2 will learn one routine for the holiday show and one routine for the summer recital.",
            notice: "*Completion of Jazz 1 Required",
            src: jazz2,
            alt: "Person Jumping and Stretching",
            ages: "7 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Black Leotard, Black or Nude  Tights, Nude Jazz Shoes",
            href: "",
            name: "Jazz 2",
        },
        {
            id: "hiphop",
            title: "Hip Hop 1",
            subclass: "",
            description: "Hip Hop 1 is available for any student looking for a fun, positive, up beat and energetic class. Dancers are always encouraged to express their personalities in the movements and exhibit confidence and showmanship. Hip Hop 1 students will learn basic isolations, and popular hip hop moves through the decades and choreography to their favorite songs. Hip Hop 1 will learn one routine for the holiday show and one routine for the summer recital.",
            notice: "",
            src: hiphop1,
            alt: "Hip Hop Dancing",
            ages: "9 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Comfortable athletic Clothes (no jeans), Tennis Shoes",
            href: "",
            name: "Hip Hop 1",
        },
        {
            id: "",
            title: "Hip Hop 2",
            subclass: "",
            description: "Hip Hop 2 is a continuation of Hip Hop 1. Dancers are always encouraged to express their personalities in the movements and exhibit confidence and showmanship. Hip Hop 2 students will continue to learn isolations, popular hip hop moves through the decades and choreography to their favorite songs. Hip Hop 2 will learn one routine for the holiday show and one routine for the summer recital.",
            notice: "*Completion of Hip Hop 1 Required",
            src: hiphop2,
            alt: "Person doing a Back Flip",
            ages: "9 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Comfortable athletic Clothes (no jeans), Tennis Shoes",
            href: "",
            name: "Hip Hop 2",
        },
        {
            id: "modernmini",
            title: "Modern Mini",
            subclass: "",
            description: "Modern Mini is for the free spirited young dancer, learning to speak and tell stories with movement. Lesson plans consist of improvisation exercises, body isolations and creative movement games. Modern Mini will learn one routine for the holiday show and one routine for the summer recital.",
            notice: "",
            src: modernmini,
            alt: "Aligned Right Arm Stretch",
            ages: "5-8 Years",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Black Leotard, Black Leggings or Tights, Bare Foot or Lyrical Shoes",
            href: "",
            name: "Modern Mini",
        },
        {
            id: "contemp",
            title: "Contemporary 1",
            subclass: "",
            description: "Contemporary dance can only be explained as 'the best of each genre'. This class encompasses ballet, jazz, modern and lyrical styles molded into Contemporary dance to show expression, grounded use of gravity and fluidity in musical comprehension. Students will also use improvisational dance to show their unique styles. Contemporary will learn one routine for the holiday show and one routine for the summer recital.",
            notice: "",
            src: contemporary1,
            alt: "Foot Point",
            ages: "9 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Dance Leotard (color optional), Dance Shorts and/or Tights, Nude Jazz Shoes",
            href: "",
            name: "Contemporary 1",
        },
        {
            id: "danceteam",
            title: "Dance Team Prep 1",
            subclass: "",
            description: "Prepare to try out for your middle school or high school dance team by learning the skills expected to be in your tryout routine and what is expected from you as a candidate. Students will practice technique, learn short combinations and run through a typical tryout process to ensure confidence in each candidate and strengthen their ability to learn choreography in a timely manner. Dance Team Prep classes will not participate in recitals, as this is a technique class only.",
            notice: "",
            src: danceteamprep1,
            alt: "Dance Team Room",
            ages: "9 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Dance Leotard (color optional), Dance Shorts and/or Tights, Nude Jazz Shoes",
            href: "",
            name: "Dance Team Prep 1",
        },
        {
            id: "leapjump",
            title: "Leaps, Jumps, Turns",
            subclass: "",
            description: "Leaps, Jumps and Turns focuses on the technique of minor and major skills. All dance is filled with basic to advanced leaps, jumps and turns. This class will allow the students to brush up on their tricks so that they can create crowd pleasing dance routines in all other classes and forms of dance. Leaps, Jumps, Turns will not perform in shows. This is a technique only class, providing instruction on basic leaps, jumps and turns.",
            notice: "",
            src: leadsjumpsturns1,
            alt: "Jump High in the Sku",
            ages: "9 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Dance Leotard, Dance Shorts and/or Tights, Your choice of Dance Shoes",
            href: "",
            name: "Leaps, Jumps, Turns 1",
        },
        {
            id: "tap",
            title: "Tap 1",
            subclass: "",
            description: "... coming soon",
            notice: "",
            src: tap1,
            alt: "Mentor and Kid Tap Dancing",
            ages: "9 Years & Up",
            duration: "1 Hour",
            payment: "$65/Month",
            note: "Attire: Dance Leotard, Dance Shorts and/or Tights, Black Tap Shoes",
            href: "",
            name: "Tap 1",
        },
        // {
        //     id: "",
        //     title: "",
        //     subclass: "",
        //     description: "",
        //     src: ,
        //     alt: "",
        //     ages: "",
        //     duration: "",
        //     payment: "",
        //     note: "",
        //     href: "",
        //     name: "",
        // },
    ]

    return {
        cards
    };
};